services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_php
    ports:
      - "8081:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
      - mongo
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootp@ssw0rd
      - MYSQL_DATABASE=bleet
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootp@ssw0rd
      MYSQL_DATABASE: bleet
      MYSQL_USER: usuario
      MYSQL_PASSWORD: p@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - C:/db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - C:/mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongop@ssw0rd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootp@ssw0rd
    ports:
      - "8082:80"

volumes:
  db_data:
  mongo_data:


